name: 'examples'

on:
  push:
  pull_request:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  linux:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        task: [
          {
            path: examples/axisbuffer/test/py,
            cmd: python3 sim.py -v
          },
          {
            path: examples/axisbuffer,
            cmd: python3 run.py
          },
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: |
        docker run --rm -tv $(pwd):/src -e PYTHONPATH="/src/VUnit/vunit:/src/VUnit/cosim" -w /src/${{ matrix.task.path }} aptman/dbhi:bionic ${{ matrix.task.cmd }}
