name: 'pynq'

on:
  push:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  pynq:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run setup_pynq.sh in arm32v7/ubuntu:bionic
      run: |
        docker run --rm --privileged aptman/qus -- -r
        docker run --rm --privileged aptman/qus -s -- -p arm
        mkdir ../build-tmp
        cd ../build-tmp
        cp ../dbhi/scripts/setup_pynq.sh ./
        docker run --rm -v $(pwd):/src -w /src arm32v7/ubuntu:bionic ./setup_pynq.sh
